live:
  hls-path: /home/ubuntu/hls

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  max-http-header-size : 10000000

#logging level
logging:
  level:
    root: trace
