live:
  hls-path: /home/ubuntu/hls
  radio-path: /home/ubuntu/radio

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  max-http-request-header-size: 10000000
