live:
  hls-path: /home/ubuntu/hls
  radio-path: /home/ubuntu/radio

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      database: chat
      host: localhost
      port: 27017
      username: root
      password: root

server:
  max-http-request-header-size: 10000000
